# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Actions/checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip        
        pip install -r requirements.txt
        pip install flake8 pylint pytest tensorflow==2.4.0-rc0
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 api/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 api/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Analyzing the code with pylint
      run: |
        pylint api/ --disable=W0511,W0105,C0103
    - name: Test with pytest
      run: |
        pytest api/
