# This workflow will install, run tests and build the UI using Yarn

name: UI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test UI
    runs-on: ubuntu-latest
    steps:
    - name: Actions/checkout
      uses: actions/checkout@v2
    - name: Set up Node.js v15
      uses: actions/setup-node@v2
      with:
        node-version: '15'
    - name: Install JS dependencies
      run: cd static/ && yarn install
    - name: Build
      run: cd static/ && yarn build
    - name: Test
      run: cd static/ && yarn test
