  
name: Yarn

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: Build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    - name: Test
      uses: CultureHQ/actions-yarn@master
      with:
        args: test
